/*
 * generated by Xtext 2.32.0
 */
package org.xtext.algorithme.algo.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AlgoAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/algorithme/algo/parser/antlr/internal/InternalAlgo.tokens");
	}
}
