/*
 * generated by Xtext 2.32.0
 */
package org.xtext.algorithme.algo.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.algorithme.algo.parser.antlr.internal.InternalAlgoParser;
import org.xtext.algorithme.algo.services.AlgoGrammarAccess;

public class AlgoParser extends AbstractAntlrParser {

	@Inject
	private AlgoGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAlgoParser createParser(XtextTokenStream stream) {
		return new InternalAlgoParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Catalogue";
	}

	public AlgoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AlgoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
