<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SchemaTable" nsURI="http://schematable" nsPrefix="schematable">
  <eClassifiers xsi:type="ecore:EClass" name="SchemaDeTable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colonnes" lowerBound="1"
        upperBound="-1" eType="#//Colonne" containment="true" eOpposite="#//Colonne/schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colonneLignes" lowerBound="1"
        eType="#//Colonne"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Colonne" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifiant" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeDonnees" lowerBound="1"
        eType="ecore:EEnum ../AlgorithmeTable/AlgorithmeTable.ecore#//TypeDonnees"
        defaultValueLiteral="Flottant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contraintes" upperBound="-1"
        eType="ecore:EClass ../AlgorithmeTable/AlgorithmeTable.ecore#//Algorithme"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" lowerBound="1"
        eType="#//SchemaDeTable" eOpposite="#//SchemaDeTable/colonnes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColonneBrute" eSuperTypes="#//Colonne"/>
  <eClassifiers xsi:type="ecore:EClass" name="ColonneCalculee" eSuperTypes="#//Colonne">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithme" lowerBound="1"
        eType="ecore:EClass ../AlgorithmeTable/AlgorithmeTable.ecore#//Algorithme"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifiantsColonnesEntree"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColonneEtrangere" eSuperTypes="#//Colonne">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nomColonneEtrangere" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schemaEntree" lowerBound="1"
        eType="#//SchemaDeTable"/>
  </eClassifiers>
</ecore:EPackage>
