/**
 * generated by Xtext 2.32.0
 */
package org.xtext.algorithme.algo.algo;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.algorithme.algo.algo.AlgoFactory
 * @model kind="package"
 * @generated
 */
public interface AlgoPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "algo";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/algorithme/algo/Algo";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "algo";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AlgoPackage eINSTANCE = org.xtext.algorithme.algo.algo.impl.AlgoPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.algorithme.algo.algo.impl.CatalogueImpl <em>Catalogue</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.algorithme.algo.algo.impl.CatalogueImpl
   * @see org.xtext.algorithme.algo.algo.impl.AlgoPackageImpl#getCatalogue()
   * @generated
   */
  int CATALOGUE = 0;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATALOGUE__NOM = 0;

  /**
   * The feature id for the '<em><b>Algorithmes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATALOGUE__ALGORITHMES = 1;

  /**
   * The number of structural features of the '<em>Catalogue</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATALOGUE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.algorithme.algo.algo.impl.AlgorithmeImpl <em>Algorithme</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.algorithme.algo.algo.impl.AlgorithmeImpl
   * @see org.xtext.algorithme.algo.algo.impl.AlgoPackageImpl#getAlgorithme()
   * @generated
   */
  int ALGORITHME = 1;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME__NOM = 0;

  /**
   * The feature id for the '<em><b>Documentation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME__DOCUMENTATION = 1;

  /**
   * The feature id for the '<em><b>Ressource</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME__RESSOURCE = 2;

  /**
   * The feature id for the '<em><b>Port</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME__PORT = 3;

  /**
   * The number of structural features of the '<em>Algorithme</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.algorithme.algo.algo.impl.RessourceImpl <em>Ressource</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.algorithme.algo.algo.impl.RessourceImpl
   * @see org.xtext.algorithme.algo.algo.impl.AlgoPackageImpl#getRessource()
   * @generated
   */
  int RESSOURCE = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESSOURCE__TYPE = 0;

  /**
   * The feature id for the '<em><b>Emplacement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESSOURCE__EMPLACEMENT = 1;

  /**
   * The number of structural features of the '<em>Ressource</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESSOURCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.algorithme.algo.algo.impl.PortImpl <em>Port</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.algorithme.algo.algo.impl.PortImpl
   * @see org.xtext.algorithme.algo.algo.impl.AlgoPackageImpl#getPort()
   * @generated
   */
  int PORT = 3;

  /**
   * The feature id for the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT__DIRECTION = 0;

  /**
   * The feature id for the '<em><b>Constant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT__CONSTANT = 1;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT__NOM = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT__TYPE = 3;

  /**
   * The number of structural features of the '<em>Port</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.algorithme.algo.algo.TypeRessource <em>Type Ressource</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.algorithme.algo.algo.TypeRessource
   * @see org.xtext.algorithme.algo.algo.impl.AlgoPackageImpl#getTypeRessource()
   * @generated
   */
  int TYPE_RESSOURCE = 4;

  /**
   * The meta object id for the '{@link org.xtext.algorithme.algo.algo.Direction <em>Direction</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.algorithme.algo.algo.Direction
   * @see org.xtext.algorithme.algo.algo.impl.AlgoPackageImpl#getDirection()
   * @generated
   */
  int DIRECTION = 5;

  /**
   * The meta object id for the '{@link org.xtext.algorithme.algo.algo.TypeDonnees <em>Type Donnees</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.algorithme.algo.algo.TypeDonnees
   * @see org.xtext.algorithme.algo.algo.impl.AlgoPackageImpl#getTypeDonnees()
   * @generated
   */
  int TYPE_DONNEES = 6;


  /**
   * Returns the meta object for class '{@link org.xtext.algorithme.algo.algo.Catalogue <em>Catalogue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Catalogue</em>'.
   * @see org.xtext.algorithme.algo.algo.Catalogue
   * @generated
   */
  EClass getCatalogue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.algorithme.algo.algo.Catalogue#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see org.xtext.algorithme.algo.algo.Catalogue#getNom()
   * @see #getCatalogue()
   * @generated
   */
  EAttribute getCatalogue_Nom();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.algorithme.algo.algo.Catalogue#getAlgorithmes <em>Algorithmes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Algorithmes</em>'.
   * @see org.xtext.algorithme.algo.algo.Catalogue#getAlgorithmes()
   * @see #getCatalogue()
   * @generated
   */
  EReference getCatalogue_Algorithmes();

  /**
   * Returns the meta object for class '{@link org.xtext.algorithme.algo.algo.Algorithme <em>Algorithme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Algorithme</em>'.
   * @see org.xtext.algorithme.algo.algo.Algorithme
   * @generated
   */
  EClass getAlgorithme();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.algorithme.algo.algo.Algorithme#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see org.xtext.algorithme.algo.algo.Algorithme#getNom()
   * @see #getAlgorithme()
   * @generated
   */
  EAttribute getAlgorithme_Nom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.algorithme.algo.algo.Algorithme#getDocumentation <em>Documentation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Documentation</em>'.
   * @see org.xtext.algorithme.algo.algo.Algorithme#getDocumentation()
   * @see #getAlgorithme()
   * @generated
   */
  EAttribute getAlgorithme_Documentation();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.algorithme.algo.algo.Algorithme#getRessource <em>Ressource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ressource</em>'.
   * @see org.xtext.algorithme.algo.algo.Algorithme#getRessource()
   * @see #getAlgorithme()
   * @generated
   */
  EReference getAlgorithme_Ressource();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.algorithme.algo.algo.Algorithme#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Port</em>'.
   * @see org.xtext.algorithme.algo.algo.Algorithme#getPort()
   * @see #getAlgorithme()
   * @generated
   */
  EReference getAlgorithme_Port();

  /**
   * Returns the meta object for class '{@link org.xtext.algorithme.algo.algo.Ressource <em>Ressource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ressource</em>'.
   * @see org.xtext.algorithme.algo.algo.Ressource
   * @generated
   */
  EClass getRessource();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.algorithme.algo.algo.Ressource#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.algorithme.algo.algo.Ressource#getType()
   * @see #getRessource()
   * @generated
   */
  EAttribute getRessource_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.algorithme.algo.algo.Ressource#getEmplacement <em>Emplacement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Emplacement</em>'.
   * @see org.xtext.algorithme.algo.algo.Ressource#getEmplacement()
   * @see #getRessource()
   * @generated
   */
  EAttribute getRessource_Emplacement();

  /**
   * Returns the meta object for class '{@link org.xtext.algorithme.algo.algo.Port <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Port</em>'.
   * @see org.xtext.algorithme.algo.algo.Port
   * @generated
   */
  EClass getPort();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.algorithme.algo.algo.Port#getDirection <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Direction</em>'.
   * @see org.xtext.algorithme.algo.algo.Port#getDirection()
   * @see #getPort()
   * @generated
   */
  EAttribute getPort_Direction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.algorithme.algo.algo.Port#isConstant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Constant</em>'.
   * @see org.xtext.algorithme.algo.algo.Port#isConstant()
   * @see #getPort()
   * @generated
   */
  EAttribute getPort_Constant();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.algorithme.algo.algo.Port#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see org.xtext.algorithme.algo.algo.Port#getNom()
   * @see #getPort()
   * @generated
   */
  EAttribute getPort_Nom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.algorithme.algo.algo.Port#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.algorithme.algo.algo.Port#getType()
   * @see #getPort()
   * @generated
   */
  EAttribute getPort_Type();

  /**
   * Returns the meta object for enum '{@link org.xtext.algorithme.algo.algo.TypeRessource <em>Type Ressource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Type Ressource</em>'.
   * @see org.xtext.algorithme.algo.algo.TypeRessource
   * @generated
   */
  EEnum getTypeRessource();

  /**
   * Returns the meta object for enum '{@link org.xtext.algorithme.algo.algo.Direction <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Direction</em>'.
   * @see org.xtext.algorithme.algo.algo.Direction
   * @generated
   */
  EEnum getDirection();

  /**
   * Returns the meta object for enum '{@link org.xtext.algorithme.algo.algo.TypeDonnees <em>Type Donnees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Type Donnees</em>'.
   * @see org.xtext.algorithme.algo.algo.TypeDonnees
   * @generated
   */
  EEnum getTypeDonnees();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AlgoFactory getAlgoFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.algorithme.algo.algo.impl.CatalogueImpl <em>Catalogue</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.algorithme.algo.algo.impl.CatalogueImpl
     * @see org.xtext.algorithme.algo.algo.impl.AlgoPackageImpl#getCatalogue()
     * @generated
     */
    EClass CATALOGUE = eINSTANCE.getCatalogue();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CATALOGUE__NOM = eINSTANCE.getCatalogue_Nom();

    /**
     * The meta object literal for the '<em><b>Algorithmes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CATALOGUE__ALGORITHMES = eINSTANCE.getCatalogue_Algorithmes();

    /**
     * The meta object literal for the '{@link org.xtext.algorithme.algo.algo.impl.AlgorithmeImpl <em>Algorithme</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.algorithme.algo.algo.impl.AlgorithmeImpl
     * @see org.xtext.algorithme.algo.algo.impl.AlgoPackageImpl#getAlgorithme()
     * @generated
     */
    EClass ALGORITHME = eINSTANCE.getAlgorithme();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHME__NOM = eINSTANCE.getAlgorithme_Nom();

    /**
     * The meta object literal for the '<em><b>Documentation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHME__DOCUMENTATION = eINSTANCE.getAlgorithme_Documentation();

    /**
     * The meta object literal for the '<em><b>Ressource</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHME__RESSOURCE = eINSTANCE.getAlgorithme_Ressource();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHME__PORT = eINSTANCE.getAlgorithme_Port();

    /**
     * The meta object literal for the '{@link org.xtext.algorithme.algo.algo.impl.RessourceImpl <em>Ressource</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.algorithme.algo.algo.impl.RessourceImpl
     * @see org.xtext.algorithme.algo.algo.impl.AlgoPackageImpl#getRessource()
     * @generated
     */
    EClass RESSOURCE = eINSTANCE.getRessource();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESSOURCE__TYPE = eINSTANCE.getRessource_Type();

    /**
     * The meta object literal for the '<em><b>Emplacement</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESSOURCE__EMPLACEMENT = eINSTANCE.getRessource_Emplacement();

    /**
     * The meta object literal for the '{@link org.xtext.algorithme.algo.algo.impl.PortImpl <em>Port</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.algorithme.algo.algo.impl.PortImpl
     * @see org.xtext.algorithme.algo.algo.impl.AlgoPackageImpl#getPort()
     * @generated
     */
    EClass PORT = eINSTANCE.getPort();

    /**
     * The meta object literal for the '<em><b>Direction</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PORT__DIRECTION = eINSTANCE.getPort_Direction();

    /**
     * The meta object literal for the '<em><b>Constant</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PORT__CONSTANT = eINSTANCE.getPort_Constant();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PORT__NOM = eINSTANCE.getPort_Nom();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PORT__TYPE = eINSTANCE.getPort_Type();

    /**
     * The meta object literal for the '{@link org.xtext.algorithme.algo.algo.TypeRessource <em>Type Ressource</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.algorithme.algo.algo.TypeRessource
     * @see org.xtext.algorithme.algo.algo.impl.AlgoPackageImpl#getTypeRessource()
     * @generated
     */
    EEnum TYPE_RESSOURCE = eINSTANCE.getTypeRessource();

    /**
     * The meta object literal for the '{@link org.xtext.algorithme.algo.algo.Direction <em>Direction</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.algorithme.algo.algo.Direction
     * @see org.xtext.algorithme.algo.algo.impl.AlgoPackageImpl#getDirection()
     * @generated
     */
    EEnum DIRECTION = eINSTANCE.getDirection();

    /**
     * The meta object literal for the '{@link org.xtext.algorithme.algo.algo.TypeDonnees <em>Type Donnees</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.algorithme.algo.algo.TypeDonnees
     * @see org.xtext.algorithme.algo.algo.impl.AlgoPackageImpl#getTypeDonnees()
     * @generated
     */
    EEnum TYPE_DONNEES = eINSTANCE.getTypeDonnees();

  }

} //AlgoPackage
