/**
 * generated by Xtext 2.32.0
 */
package org.xtext.algorithme.algo.algo;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.algorithme.algo.algo.AlgoPackage
 * @generated
 */
public interface AlgoFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AlgoFactory eINSTANCE = org.xtext.algorithme.algo.algo.impl.AlgoFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Catalogue</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Catalogue</em>'.
   * @generated
   */
  Catalogue createCatalogue();

  /**
   * Returns a new object of class '<em>Algorithme</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Algorithme</em>'.
   * @generated
   */
  Algorithme createAlgorithme();

  /**
   * Returns a new object of class '<em>Ressource</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ressource</em>'.
   * @generated
   */
  Ressource createRessource();

  /**
   * Returns a new object of class '<em>Port</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Port</em>'.
   * @generated
   */
  Port createPort();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AlgoPackage getAlgoPackage();

} //AlgoFactory
