/**
 * generated by Xtext 2.32.0
 */
package org.xtext.algorithme.algo.algo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Port</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.algorithme.algo.algo.Port#getDirection <em>Direction</em>}</li>
 *   <li>{@link org.xtext.algorithme.algo.algo.Port#isConstant <em>Constant</em>}</li>
 *   <li>{@link org.xtext.algorithme.algo.algo.Port#getNom <em>Nom</em>}</li>
 *   <li>{@link org.xtext.algorithme.algo.algo.Port#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.algorithme.algo.algo.AlgoPackage#getPort()
 * @model
 * @generated
 */
public interface Port extends EObject
{
  /**
   * Returns the value of the '<em><b>Direction</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.algorithme.algo.algo.Direction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direction</em>' attribute.
   * @see org.xtext.algorithme.algo.algo.Direction
   * @see #setDirection(Direction)
   * @see org.xtext.algorithme.algo.algo.AlgoPackage#getPort_Direction()
   * @model
   * @generated
   */
  Direction getDirection();

  /**
   * Sets the value of the '{@link org.xtext.algorithme.algo.algo.Port#getDirection <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direction</em>' attribute.
   * @see org.xtext.algorithme.algo.algo.Direction
   * @see #getDirection()
   * @generated
   */
  void setDirection(Direction value);

  /**
   * Returns the value of the '<em><b>Constant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant</em>' attribute.
   * @see #setConstant(boolean)
   * @see org.xtext.algorithme.algo.algo.AlgoPackage#getPort_Constant()
   * @model
   * @generated
   */
  boolean isConstant();

  /**
   * Sets the value of the '{@link org.xtext.algorithme.algo.algo.Port#isConstant <em>Constant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant</em>' attribute.
   * @see #isConstant()
   * @generated
   */
  void setConstant(boolean value);

  /**
   * Returns the value of the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nom</em>' attribute.
   * @see #setNom(String)
   * @see org.xtext.algorithme.algo.algo.AlgoPackage#getPort_Nom()
   * @model
   * @generated
   */
  String getNom();

  /**
   * Sets the value of the '{@link org.xtext.algorithme.algo.algo.Port#getNom <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nom</em>' attribute.
   * @see #getNom()
   * @generated
   */
  void setNom(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.algorithme.algo.algo.TypeDonnees}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.algorithme.algo.algo.TypeDonnees
   * @see #setType(TypeDonnees)
   * @see org.xtext.algorithme.algo.algo.AlgoPackage#getPort_Type()
   * @model
   * @generated
   */
  TypeDonnees getType();

  /**
   * Sets the value of the '{@link org.xtext.algorithme.algo.algo.Port#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.algorithme.algo.algo.TypeDonnees
   * @see #getType()
   * @generated
   */
  void setType(TypeDonnees value);

} // Port
