/**
 * generated by Xtext 2.32.0
 */
package org.xtext.algorithme.algo.algo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ressource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.algorithme.algo.algo.Ressource#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.algorithme.algo.algo.Ressource#getEmplacement <em>Emplacement</em>}</li>
 * </ul>
 *
 * @see org.xtext.algorithme.algo.algo.AlgoPackage#getRessource()
 * @model
 * @generated
 */
public interface Ressource extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.algorithme.algo.algo.TypeRessource}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.algorithme.algo.algo.TypeRessource
   * @see #setType(TypeRessource)
   * @see org.xtext.algorithme.algo.algo.AlgoPackage#getRessource_Type()
   * @model
   * @generated
   */
  TypeRessource getType();

  /**
   * Sets the value of the '{@link org.xtext.algorithme.algo.algo.Ressource#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.algorithme.algo.algo.TypeRessource
   * @see #getType()
   * @generated
   */
  void setType(TypeRessource value);

  /**
   * Returns the value of the '<em><b>Emplacement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Emplacement</em>' attribute.
   * @see #setEmplacement(String)
   * @see org.xtext.algorithme.algo.algo.AlgoPackage#getRessource_Emplacement()
   * @model
   * @generated
   */
  String getEmplacement();

  /**
   * Sets the value of the '{@link org.xtext.algorithme.algo.algo.Ressource#getEmplacement <em>Emplacement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Emplacement</em>' attribute.
   * @see #getEmplacement()
   * @generated
   */
  void setEmplacement(String value);

} // Ressource
