/*
 * generated by Xtext 2.32.0
 */
package org.xtext.algorithme.algo.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.algorithme.ui.internal.AlgorithmeActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AlgoExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(AlgorithmeActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		AlgorithmeActivator activator = AlgorithmeActivator.getInstance();
		return activator != null ? activator.getInjector(AlgorithmeActivator.ORG_XTEXT_ALGORITHME_ALGO_ALGO) : null;
	}

}
