/*
 * generated by Xtext 2.32.0
 */
package org.xtext.algorithme.algo.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAlgoScopeProvider extends DelegatingScopeProvider {
}
