/*
 * generated by Xtext 2.32.0
 */
package org.xtext.algorithme.algo.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractAlgoValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.algorithme.algo.algo.AlgoPackage.eINSTANCE);
		return result;
	}
}
