/*
 * generated by Xtext 2.32.0
 */
package org.xtext.algorithme.algo.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.algorithme.ui.internal.AlgorithmeActivator;

public class AlgoUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AlgorithmeActivator.getInstance().getInjector("org.xtext.algorithme.algo.Algo");
	}

}
