/*
 * generated by Xtext 2.32.0
 */
package org.xtext.algorithme.algo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AlgoUiModule extends AbstractAlgoUiModule {

	public AlgoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
