/**
 * generated by Xtext 2.32.0
 */
package org.xtext.algorithme.algo.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(AlgoInjectorProvider.class)
@SuppressWarnings("all")
public class AlgoParsingTest {
  @Inject
  private /* ParseHelper<Model> */Object parseHelper;

  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field AlgoParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
