/*
 * generated by Xtext 2.32.0
 */
package org.xtext.algorithme.algo.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class AlgoOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
